print (5 + 8)
print ( show ( 3 * 5 + 8))
print ( show ( + 2 8))
print ( show ( sqrt 16))
print ( show ( succ 8))
print ( show ( pred 9))
print ( show ( sin (pi / 2 )))
print ( show ( truncate pi))
print ( show ( round 3.5))
print ( show ( round 3.4))
print ( show ( floor 3.7))
print ( show ( ceiling 3.7))
